# fly.toml app configuration file generated for fishfolioapi on 2023-10-16T16:07:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fishfolioapi"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[env]
  CLIENT_ORIGIN = "https://fishfolio.netlify.app"
  MONGODB_URI = "mongodb+srv://brendin0702:Acquire0702@brendinsdb.hkap1tw.mongodb.net/fishFolio?retryWrites=true&w=majority"
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
